### ISSUE TITLE
Parameter estimation: the Lorentz example

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqDocs.jl#10]
Replacating the Lotka Volterra estimation for the Lorentz example:

g = @ode_def LorenzExample begin
#g = @ode_def_nohes LorenzExample begin
  dx = σ*(y-x)
  dy = x*(ρ-z) - y
  dz = x*y - β*z
end σ=>10.0 ρ=>28.0 β=(8/3)

u0 = [1.0;0.0;0.0]
tspan = (0.0,1.0)
prob = ODEProblem(g,u0,tspan)

What is the correct syntax for generating the same data as PODES (span 0 to 30 with 500 data points)?

sol = solve(prob,Tsit5())
t = collect(linspace(0,30,500))
randomized = [(sol(t[i]) + .01randn(2)) for i in 1:length(t)]

Could not remember any docs about data generation.

**Comment by ChrisRackauckas** [comment]
You need to use random vectors which have 3 components instead of two:

```julia
randomized = [(sol(t[i]) + .01randn(3)) for i in 1:length(t)]
```

The Lorenz model will be very bad for parameter estimation since it's chaotic, and so very small errors can lead to huge differences, making it extremely hard to estimate with a local least squares regression (you probably know that).

**Comment by finmod** [comment]
This is what I inferred. I submit:

sol = solve(prob,Tsit5())
t = collect(linspace(0,30,500))
randomized = [(sol(t[i]) + .01randn(3)) for i in 1:length(t)]

It gives me the following error:

BoundsError: attempt to access 28-element Array{Int64,1} at index [0]

 in getindex(::Array{Int64,1}, ::Int64) at .\array.jl:386
 in ode_interpolation(::Float64, ::Function) at C:\Users\Denis\.julia\v0.5\OrdinaryDiffEq\src\dense.jl:80
 in (::DiffEqBase.ODESolution{Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,ParameterizedFunctions.LorenzExample},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{ParameterizedFunctions.LorenzExample,Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64}}}})(::Float64) at C:\Users\Denis\.julia\v0.5\DiffEqBase\src\solutions\ode_solutions.jl:13
 in #3 at .\<missing>:0 [inlined]
 in next at .\generator.jl:26 [inlined]
 in collect_to!(::Array{Array{Float64,1},1}, ::Base.Generator{UnitRange{Int64},##3#4}, ::Int64, ::Int64) at .\array.jl:340
 in collect(::Base.Generator{UnitRange{Int64},##3#4}) at .\array.jl:308

**Comment by ChrisRackauckas** [comment]
Oh, I thought you should know that there are potentially two summer projects by two potential Google Summer of Code students related to parameter estimation: one setting up an interface to use Stan.jl, and another directly setting up the DiffEq methods to use Mocha.jl as an MCMC engine. Also, I may be taking an internship with LLNL to make Mads.jl work directly from DiffEq functions, and add adjoint sensitivity methods. So this section of DiffEq that you're interested is looking to get a boost in the summer.

**Comment by ChrisRackauckas** [comment]
I can't test this right now since I am in the middle of finishing up a release which enhances interpolations:

**Comment by finmod** [comment]
In fact, it may have something to do with that since yesterday's issue about Pkg.test("DifferentialEquations") is giving an increasing number of errors with DiffEqBase and the requirements of everything else in DiffEq.

**Comment by ChrisRackauckas** [comment]
What's your `Pkg.status()`? DiffEqBase master currently requires master on OrdinaryDiffEq (along with StochasticDiffEq and DelayDiffEq) in order to work: these are the interpolations changes that I am doing right now. (But current release should be fine)

**Comment by finmod** [comment]
Here is my Pkg.status(). DiffBase is odd..should'nt it be DiffEqBase?

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.status()
51 required packages:
 - ArbFloats                     0.1.15
 - BaseTestNext                  0.2.2
 - CUDArt                        0.2.3+             master
 - Clp                           0.3.0
 - Combinatorics                 0.3.2+             master
 - DataFrames                    0.8.5
 - DecFP                         0.1.5              master
 - Decimals                      0.1.0
 - DiffEqBase                    0.6.0
 - DiffEqProblemLibrary          0.4.0
 - DifferentialEquations         1.6.0+             master
 - Distances                     0.3.2
 - DoubleDouble                  0.2.0
 - DualNumbers                   0.2.3
 - ForwardDiff                   0.3.4+             master
 - GLM                           0.6.1
 - GLPKMathProgInterface         0.2.3
 - GR                            0.19.0
 - Gadfly                        0.5.3
 - GaussianProcesses             0.4.0+             master
 - Graphs                        0.7.1
 - IJulia                        1.4.1
 - ImageMagick                   0.2.0+             master
 - Interact                      0.4.3
 - Ipopt                         0.2.6
 - JuMP                          0.15.0+            master
 - Juno                          0.2.5
 - LeastSquaresOptim             0.2.1
 - Mads                          0.2.18-            master (dirty)
 - ManifoldLearning              0.1.0+             master
 - MathProgBase                  0.5.10
 - MatlabCompat                  0.1.2+             master
 - NLsolve                       0.9.1
 - Nemo                          0.5.1
 - ODE                           0.2.1+             master
 - ODEInterface                  0.1.0
 - OrdinaryDiffEq                1.0.2
 - ParallelDataTransfer          0.1.1
 - ParameterizedFunctions        0.6.0
 - PyCall                        1.9.0              master
 - PyPlot                        2.2.4
 - QuantEcon                     0.8.0
 - RDatasets                     0.2.0
 - ReverseDiffSource             0.3.0
 - ReverseDiffSparse             0.7.0
 - Roots                         0.3.0
 - ScikitLearn                   0.2.3+             master
 - StatPlots                     0.2.1
 - Sundials                      0.7.0+             master
 - SymEngine                     0.1.2+             master
 - Unitful                       0.0.4+             master
153 additional packages:
 - AffineInvariantMCMC           0.1.3
 - AlgebraicDiffEq               0.1.0
 - Anasol                        0.1.10
 - AutoHashEquals                0.0.10
 - AxisAlgorithms                0.1.5
 - AxisArrays                    0.0.3
 - BIGUQ                         0.2.0
 - BinDeps                       0.4.5
 - BlackBoxOptim                 0.2.1
 - Blosc                         0.1.7
 - BufferedStreams               0.2.3
 - CDDLib                        0.1.2
 - CUDAdrv                       0.2.1
 - Cairo                         0.2.35
 - Calculus                      0.2.0
 - CatIndices                    0.0.1
 - Cbc                           0.3.0
 - ChunkedArrays                 0.1.1
 - Codecs                        0.2.0
 - ColorTypes                    0.3.0
 - ColorVectorSpace              0.2.0
 - Colors                        0.7.0
 - Compat                        0.14.0
 - Compose                       0.4.5
 - ComputationalResources        0.0.1
 - Conda                         0.4.0
 - Contour                       0.2.0
 - CustomUnitRanges              0.0.3
 - DSP                           0.1.1
 - DataArrays                    0.3.11
 - DataStructures                0.5.2
 - Dates                         0.4.4
 - DelayDiffEq                   0.0.1+             master
 - DiffBase                      0.0.3
 - DiffEqBenchmarks              0.0.0-             master (unregistered)
 - DiffEqCallbacks               0.0.1+             master
 - DiffEqDevTools                0.6.0
 - DiffEqMonteCarlo              0.0.1+             master
 - DiffEqPDEBase                 0.0.3
 - DiffEqParamEstim              0.0.4+             master
 - DiffEqSensitivity             0.0.4
 - DiffEqTutorials               0.0.0-             master (unregistered, dirty)
 - DiffEqUncertainty             0.0.0-             master (unregistered)
 - Distributions                 0.12.0
 - DocStringExtensions           0.3.1
 - Documenter                    0.9.0
 - EllipsisNotation              0.0.2
 - FFTViews                      0.0.1
 - FactCheck                     0.4.3
 - FileIO                        0.2.2              master
 - FiniteElementDiffEq           0.2.1
 - FixedPointNumbers             0.3.0
 - FixedSizeArrays               0.2.5
 - Formatting                    0.2.0
 - GLPK                          0.3.0
 - GZip                          0.2.20
 - Games                         0.0.0-             master (unregistered)
 - GenericSVD                    0.0.2
 - GeometryTypes                 0.2.2
 - Graphics                      0.1.3
 - HDF5                          0.7.3
 - Hexagons                      0.0.4
 - Hiccup                        0.1.1
 - ImageAxes                     0.1.0
 - ImageCore                     0.1.1
 - ImageFiltering                0.1.1
 - ImageMetadata                 0.1.1
 - ImageView                     0.3.0
 - Images                        0.6.0
 - IndirectArrays                0.1.0
 - IniFile                       0.2.5
 - InplaceOps                    0.1.0
 - Interpolations                0.3.6
 - IntervalSets                  0.0.2
 - IterativeSolvers              0.2.2
 - Iterators                     0.2.0
 - JLD                           0.6.9
 - JSON                          0.8.2
 - KernelDensity                 0.3.0
 - Klara                         0.7.1
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.5
 - LearnBase                     0.1.1
 - LegacyStrings                 0.2.0
 - LibExpat                      0.2.4
 - Libz                          0.2.2
 - LightGraphs                   0.7.2
 - LightXML                      0.4.0
 - LineSearches                  0.1.5
 - Loess                         0.1.0
 - LossFunctions                 0.0.2
 - LsqFit                        0.1.1
 - MAT                           0.3.1
 - MacroTools                    0.3.4
 - MappedArrays                  0.0.5
 - Measures                      0.0.3
 - Media                         0.2.5
 - MetaProgTools                 0.1.5
 - MultivariateStats             0.3.1
 - NaNMath                       0.2.2
 - Nettle                        0.2.4
 - OffsetArrays                  0.2.12
 - Optim                         0.7.4+             master
 - PDMats                        0.5.4
 - Parameters                    0.6.0
 - ParserCombinator              1.7.11
 - PlotThemes                    0.1.0
 - PlotUtils                     0.3.0
 - Plots                         0.10.3
 - Polyhedra                     0.1.3
 - PolynomialFactors             0.0.3
 - Polynomials                   0.1.2
 - PositiveFactorizations        0.0.4
 - Primes                        0.1.2
 - ProgressMeter                 0.3.3
 - QuadGK                        0.1.1
 - RData                         0.0.4
 - RangeArrays                   0.1.1
 - Ranges                        0.0.1
 - Ratios                        0.0.4
 - Reactive                      0.3.6
 - ReadableNumbers               0.0.3
 - RecipesBase                   0.1.0
 - RecursiveArrayTools           0.2.0
 - Reexport                      0.0.3
 - Requires                      0.3.0
 - ResettableStacks              0.0.1
 - ReusableFunctions             0.1.11
 - Rmath                         0.1.6
 - RobustPmap                    0.1.12
 - SHA                           0.3.0
 - SIUnits                       0.1.0
 - ScikitLearnBase               0.2.1
 - ShowItLikeYouBuildIt          0.0.1
 - Showoff                       0.0.7
 - SimpleTraits                  0.2.0
 - SortingAlgorithms             0.1.0
 - StaticArrays                  0.1.4
 - StatsBase                     0.13.0
 - StatsFuns                     0.4.0
 - StochasticDiffEq              0.5.0
 - StokesDiffEq                  0.1.0
 - TexExtensions                 0.0.3
 - TiledIteration                0.0.1
 - Tk                            0.4.0
 - URIParser                     0.1.7
 - VectorizedRoutines            0.0.2
 - WinRPM                        0.2.3
 - Winston                       0.12.1
 - WoodburyMatrices              0.2.1
 - YAML                          0.1.10
 - ZMQ                           0.4.1
 - Zlib                          0.1.12

julia>

**Comment by ChrisRackauckas** [comment]
JuliaDiff has DiffBase for ForwardDiff/ReverseDiff.

I found your issue last night, and it was due to versioning problems:

https://github.com/JuliaLang/METADATA.jl/pull/7784

The next release should be out soon.

**Comment by finmod** [comment]
Commenting on some of the steps of the Roadmap you outlined above, the nexus "parameter estimation - stan.jl" does not appear this important to me because these statistical methods do not deal much with the essence of differential equation systems. Concerning Mocha.jl, this is more interesting because it deals well with parallel computing, GPU and CUDA computing on laptops. I noticed that you are already doing quite well in this direction with the latest DiffEqBenchmarks.

The all important White paper for DiffEq is "The Bayesian approach to Inverse Problems" by Masoumeh Dashti and Andrew Stuart (arXiv 2015). There, you find a unified framework dealing with all types of DiffEq, all types of posterior distributions and the MCMCs. Here, PODES is one of the prototypes and Mads.jl has the same overall approach with additional advantage of dealing with dimensionality reduction via Tikhonov regularization. At this point, there are two recent developments in the estimation of inverse problems. First is "likelihood-informed parameter and state reduction" by Cui, Marzouk and Willcox (2016) and the second is "Geometric MCMC   for infinite dimensional inverse problems" by Andrew Stuart et al. (2016). Unfortunately, each group of authors deals with different computer software: Mads is in Julia, PODES is in Matlab, Likelihood-informed deals in C++ and MUQ library and Stuart deals in Matlab and Python.

Your interest and consideration of coupling Mads and DiffEQ within Julia is the right direction. I am evaluating myself Mads examples but I have constant difficulties with running Mads in Windows because the authors use Ubuntu. Progress is slow. It would be good to see if Algorithm 1 of Cui, Marzouk and Willcox can be set up in Julia with bits already put together by Mads.jl (calibrate, BIGUQ). Finally, the algorithms in GeoMCMC could also be built directly in Julia. The forward model and the data-misfit function should be able to deal with a family of metrics (Hellinger and others) and a family of regularizations within the same unified body.

**Comment by finmod** [comment]
Let me report on the use of autodiff=true with Optim. The option is running fine now. Here is a report on the outcomes with the various options in Optim for the Lotke-Volterra example:

 #@time result = optimize(cost_function, x, BFGS(), Optim.Options(autodiff = true)) # Pass. Single precision
@time result = optimize(cost_function, x, LBFGS(), Optim.Options(autodiff = true)) # Pass. Single precision 0.43 seconds
#@time result = optimize(cost_function, x, ConjugateGradient(), Optim.Options(autodiff = true)) # Pass. Single precision
#@time result = optimize(cost_function, x, GradientDescent(), Optim.Options(autodiff = true)) # Pass. No precision
#@time result = optimize(cost_function, x, MomentumGradientDescent(), Optim.Options(autodiff = true)) # Pass. No precision
#@time result = optimize(cost_function, x, AcceleratedGradientDescent(), Optim.Options(autodiff = true)) # Pass. No precision
#@time result = optimize(cost_function, x, Newton(), Optim.Options(autodiff = true)) # Pass. No precision

It would be good to know if LeastSquaresOptim has an autodiff option working for Dogleg and LM but no reply to my query so far from Matthieu Gomez. LeastSquaresOptim remains the most efficient method.

Finally, the introduction of NLopt is pretty bad from the methods point of view. Only GN_ISRES can produce the correct parameter estimates and not very efficiently. I will open a new issue about build_loss_objective because this is about how the estimation is set up and not so much about the efficiency of various solvers.

You may close this issue.
