### ISSUE TITLE
Document the Adams methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDocs.jl#103]
@sipah00

**Comment by sipah00** [comment]
Sure, I will do asap.

**Comment by ChrisRackauckas** [comment]
Bump

**Comment by sipah00** [comment]
@ChrisRackauckas, can you tell me what things should I include in the documentation of Adams methods except how to use and parameters of the methods.

**Comment by ChrisRackauckas** [comment]
Just follow the others: http://docs.juliadiffeq.org/latest/solvers/ode_solve.html

**Comment by sipah00** [comment]
@ChrisRackauckas, shouldn't we include this example ?
```julia
solve(prob,AB3(),dt=0.2)
```

**Comment by ChrisRackauckas** [comment]
Nah, it's not necessary. It doesn't add anything that the other examples don't. Thanks though!
