### ISSUE TITLE
Parameter estimation docs outdated

### ISSUE THREAD

**Issue by danielwe** [JuliaDiffEq/DiffEqDocs.jl#108]
The paragraph on the problem generator function,
https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/b11c9da2bdb6c3c7f9ca8152a62eb977b014987f/docs/src/analysis/parameter_estimation.md#the-problem-generator-function
doesn't reflect the current state of the code.
https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/0d5277939e027bfa1962ae0c3bde8cc275b1a480/src/parameters_interface.jl#L1
Most importantly, there's no wrapping of `f` now that parameters are passed around explicitly.

**Comment by ChrisRackauckas** [comment]
Thanks! Updated.

**Comment by danielwe** [comment]
I think there's still a sentence that's out of date: "By default, this just builds a new version of `f` that inserts all of the parameters." Didn't want to touch this myself because I'm not very familiar with what's going on here, but it seems like in the current rendition, `problem_new_parameters` does nothing but modify the element types for `u0` and `tspan`.

**Comment by danielwe** [comment]
...and instantiate an ODEProblem with the new `p`, of course.

**Comment by ChrisRackauckas** [comment]
Yes, I was too hasty. Round 2.
