### ISSUE TITLE
Append "!" to mutating functions in examples to follow style guide

### ISSUE THREAD

**Issue by non-Jedi** [JuliaDiffEq/DiffEqDocs.jl#114]
https://docs.julialang.org/en/stable/manual/style-guide/#Append-!-to-names-of-functions-that-modify-their-arguments-1

Not a ton of benefit here, I think, but I did just manage to confuse myself reading an example because I forgot that a function modified `out` rather than returning dy. Would be good to switch everything over to following that part of the style guide eventually.

Then again, many of these functions are called simply "f" and are treated more or less as anonymous functions. There seems to be a strong convention throughout a lot of tutorials/docs to call those kind of functions "f" rather than "f!". I don't personally think this is a good convention but would understand if that's the direction chosen.

**Comment by ChrisRackauckas** [comment]
Yeah, I've been meaning to do it. They should probably all put `!` on the end when they are in the in-place form. I'll accept PRs but won't be rushing to do it myself since it's a little tedious for not too much benefit.

**Comment by ChrisRackauckas** [comment]
I think we've done this in most places now. Specific ones should get caught and changed. Thanks!
