### ISSUE TITLE
Add first-differences distributions to parameter estimation docs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDocs.jl#123]
@Vaibhavdixit02

**Comment by Vaibhavdixit02** [comment]
http://docs.juliadiffeq.org/latest/analysis/parameter_estimation.html#First-differencing-1, should be closed?

**Comment by ChrisRackauckas** [comment]
Is this ever shown in an example?

**Comment by ChrisRackauckas** [comment]
Then one should be added to the docs. An example of the two stage methods should be added as well.
