### ISSUE TITLE
Add control problem for callbacks docs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDocs.jl#14]
It's a good way to show how to use `tstops` with `DiscreteCallback` together. @ronisbr

**Comment by ronisbr** [comment]
Hi @ChrisRackauckas,

What do you think about a simplified version of this problem:

http://www.ronanarraes.com/2017/02/extending-the-ode-solutions-in-julia-by-creating-custom-data-arrays-for-the-simulations/

which is a simple discrete controller to control the position of a particle.

**Comment by ChrisRackauckas** [comment]
Oh, that reminds me that I do have this

http://docs.juliadiffeq.org/latest/features/data_arrays.html#Example:-A-Control-Problem-1

I might want to just link over to it. But I'd like to try and keep different ideas separate so that way the examples are simple. Hmm...
