### ISSUE TITLE
ODE constructor does not support `mass_matrix` keyword anymore

### ISSUE THREAD

**Issue by timkittel** [JuliaDiffEq/DiffEqDocs.jl#153]
The docs should be updated to reflect that the `mass_matrix` keyword moved from  ODEProblem constructors to ODEFunction constructors.\
see http://docs.juliadiffeq.org/latest/types/ode_types.html#Constructors-1

**Comment by ChrisRackauckas** [comment]
Done

**Comment by timkittel** [comment]
awesome!
