### ISSUE TITLE
A bunch of new issues due to v1.0

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDocs.jl#160]
https://travis-ci.org/JuliaDiffEq/DiffEqDocs.jl/jobs/432562826#L611-L711

**Comment by tkf** [comment]
Don't you need to call `importodeproblems()` etc?  Also, maybe it would be nice to pass `strict = true` to `makedocs` to catch this kind of regression early?

**Comment by ChrisRackauckas** [comment]
Yes, setting it to strict is probably a good idea.
