### ISSUE TITLE
DiffEqProblemLibrary examples broken

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqDocs.jl#171]
From the ODE problem types page:

```
using DiffEqProblemLibrary
prob = prob_ode_linear
sol = solve(prob)
```

doesn't seem to work anymore. This, and the related SDE/DAE examples, need to be updated for the new submodule form of DiffEqProblemLibrary.

**Comment by ChrisRackauckas** [comment]
Thanks. Yes, that needs to be updated.
