### ISSUE TITLE
Solving a forced SDE

### ISSUE THREAD

**Issue by Omer80** [JuliaDiffEq/DiffEqDocs.jl#173]
Which solvers from the ones implemented in JuliaDiffEq would you recommend for a forced SDE system , where the forced is additive as in the form:
`du = a*cos(omega_f*t)dt+ f(u,p)dt + g(u,p,t)dW`

**Comment by ChrisRackauckas** [comment]
There's no differential on the forcing? That would make it infinite?

**Comment by Omer80** [comment]
Oops, the differential on the forcing was missing...

**Comment by ChrisRackauckas** [comment]
so then it's just an SDE? define `h(u,p) = a*cos(omega_f*t)+ f(u,p)` and solve the SDE `du = h(u,p)dt + g(u,p,t)dW`
