### ISSUE TITLE
Function names with _ leading to italics

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaDiffEq/DiffEqDocs.jl#174]
http://docs.juliadiffeq.org/latest/analysis/parameter_estimation.html#two*stage*method-1

We should either use the name of the method such as `Two Stage Method` instead or find a way to avoid this when not required?

The first solution seems easier for the current problem but this could be a problem later on as well?

**Comment by ChrisRackauckas** [comment]
Yes, let's put spaces.
