### ISSUE TITLE
Remove anonymous definitions of user functions from docs

### ISSUE THREAD

**Issue by gabrielgellner** [JuliaDiffEq/DiffEqDocs.jl#18]
Currently the docs give simply example that use the style:
```julia
name = function (args)
  foo
end
```
instead of the more idiomatic
```julia
function name(args)
  foo
end
```
which is likely to seem strange to regular end users of the package. Once 0.6 is standard and Julia#265 is fixed the later version will likely be better from a pedagogical point of view.

**Comment by ChrisRackauckas** [comment]
Should this happen with v2.0 or wait for the release of Julia v0.6?

**Comment by gabrielgellner** [comment]
Would it cause problems if done before 0.6? I think this will make the docs far more noob friendly, but not if it causes strange behavior.

**Comment by ChrisRackauckas** [comment]
v0.5 will have strange behavior if two functions are named the same, or if the user tries to change the function after calling it once.

**Comment by gabrielgellner** [comment]
Then I would wait. I can do a PR once 0.6 is out, if you are not feeling it.

**Comment by ChrisRackauckas** [comment]
Okay. Sounds good. That completes the issue audit!

**Comment by ChrisRackauckas** [comment]
This is something we should make sure gets done. All functions should be audited to be regular and not anonymous now.

**Comment by gabrielgellner** [comment]
I am at a conference for the next two weeks, but then I will get this done!

**Comment by ChrisRackauckas** [comment]
Handled by https://github.com/JuliaDiffEq/DiffEqDocs.jl/pull/48
