### ISSUE TITLE
Wrong bulleting in homepage

### ISSUE THREAD

**Issue by kanav99** [JuliaDiffEq/DiffEqDocs.jl#184]
In the homepage, in the index of Solver Algorithms, we have something like this:

* BVP Solvers
    * Recommended Methods
* Full List of Methods
    * BoundaryValueDiffEq.jl

Though I think it should be:

* BVP Solvers
    * Recommended Methods
    * Full List of Methods
        * BoundaryValueDiffEq.jl

**Comment by ChrisRackauckas** [comment]
Do we have a third nest in the docs? Anyways, changing this is just changing the depth of the header.
