### ISSUE TITLE
SSPRK Methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDocs.jl#19]
Should add these new methods to the docs.

https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/src/solvers/ode_solve.md

@ranocha

**Comment by ChrisRackauckas** [comment]
@ranocha , can I get a good citation as well?

https://github.com/JuliaDiffEq/juliadiffeq.github.io/blob/master/citing.md

Is it the Ketchenson paper?

**Comment by ranocha** [comment]
The citations are:

- General: Gottlieb, Sigal, David I. Ketcheson, and Chi-Wang Shu. Strong stability preserving Runge-Kutta and multistep time discretizations. World Scientific, 2011.
- `SSPRK22` and `SSPRK33`: Shu, Chi-Wang, and Stanley Osher. "Efficient implementation of essentially non-oscillatory shock-capturing schemes." Journal of Computational Physics 77.2 (1988): 439-471.
- `SSPRK104`: Ketcheson, David I. "Highly efficient strong stability-preserving Runge–Kutta methods with low-storage implementations." SIAM Journal on Scientific Computing 30.4 (2008): 2113-2136.
