### ISSUE TITLE
@ode_def_nohes macro replaced by @ode_def_all?

### ISSUE THREAD

**Issue by SuperFluffy** [JuliaDiffEq/DiffEqDocs.jl#192]
The tutorial on [Uncertainty quantification](https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/src/analysis/uncertainty_quantification.md) mentions the macro `@ode_def_nohes`. It looks like this is an artifact from the past? `ParameterizedFunctions.jl` does not mention that macro anymore, it looks like it was removed in commit d525ac12334a210f08d0224290cdfc51ae2101cd. The macro [@ode_def_all](https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/blob/master/src/macros.jl#L29) seems to be a direct replacement?

If that's the case, I can make a PR for the docs. I am technically only using Julia since Wednesday, so I can't make an educated decision.

**Comment by ChrisRackauckas** [comment]
This has been all updated.
