### ISSUE TITLE
I get a negative one step ahead value of the function although the previous step and the derivative are both positive

### ISSUE THREAD

**Issue by danielwillsr** [JuliaDiffEq/DiffEqDocs.jl#199]
I am trying to solve an 8 dimensional ODE. I am using the following code. 

 u0 = [uw0, μ0, e0, ϕ_e0, y_agg0, λ0, l_agg0, ω0]
 tspan = (exp(pa.μ_w-3*pa.σ2_w),exp(pa.μ_w+3*pa.σ2_w))
 prob = ODEProblem(find_states!,u0,tspan,pa)
 solvec=Array{OrdinaryDiffEq.ODECompositeSolution}(undef,1)
solvec[1] = solve(prob)

The derivative of the first function, uw0, cannot take negative values, and numerically it doesn't.
But after several iterations, when the time variable takes the value of 18.51712908573037, uw= 0.0032659204094832787 and the derivative is duw = 0.000636904055056477.
One step ahead, t= 18.633999279738497 but the value for uw= -0.006016597644230427 is negative.

**Comment by ChrisRackauckas** [comment]
This repo is for documentation issues, so I'm going to close it for the sake of cleanliness. 

As for your issue, did you try using tools like `PositiveCalback`, `isoutofdomain`, lower the integration `abstol` or `reltol`, reparameterize the equation, or ensure model correctness? There isn't any code for me to run so I can't really help much other than suggesting all of the common fixes.
