### ISSUE TITLE
Need to update main Docs

### ISSUE THREAD

**Issue by vaishnavtv** [JuliaDiffEq/DiffEqDocs.jl#203]
Hello,

I have just begun using the DifferentialEquations ecosystem for my multibody dynamics problems. I found a mistake in the main docs describing the [first](http://docs.juliadiffeq.org/v2.0.1/tutorials/ode_example.html) ode example. I believe the correct syntax is f(u,p,t) as the definition f(t,u) throws an error. I found the corrected syntax [here](http://juliadiffeq.org/DiffEqTutorials.jl/html/introduction/ode_introduction.html) in a notebook managed by one of the contributors here. If you could update the main documentation to reflect the changes made, it'd be greatly appreciated.

**Comment by ChrisRackauckas** [comment]
You're looking at the v2.0.1 documentation. Notice that the page for the stable release is correct: http://docs.juliadiffeq.org/stable/tutorials/ode_example.html
