### ISSUE TITLE
ode_example does not work as described

### ISSUE THREAD

**Issue by Tyde** [JuliaDiffEq/DiffEqDocs.jl#21]
Hi, 

I just wanted to do the ode_example tutorial and encountered the following problem:
When I tried to execute `sol = solve(prob)`, julia threw the following errors:
```julia
MethodError: no method matching solve(::DiffEqBase.ODEProblem{Float64,Float64,false,#f})
Closest candidates are:
  solve{uType,tType,isinplace,T<:OrdinaryDiffEq.OrdinaryDiffEqAlgorithm,F}(::DiffEqBase.AbstractODEProblem{uType,tType,isinplace,F}, ::T<:OrdinaryDiffEq.OrdinaryDiffEqAlgorithm) at C:\Users\thiem\.julia\v0.5\OrdinaryDiffEq\src\solve.jl:20
  solve{uType,tType,isinplace,T<:OrdinaryDiffEq.OrdinaryDiffEqAlgorithm,F}(::DiffEqBase.AbstractODEProblem{uType,tType,isinplace,F}, ::T<:OrdinaryDiffEq.OrdinaryDiffEqAlgorithm, ::Any) at C:\Users\thiem\.julia\v0.5\OrdinaryDiffEq\src\solve.jl:20
  solve{uType,tType,isinplace,T<:OrdinaryDiffEq.OrdinaryDiffEqAlgorithm,F}(::DiffEqBase.AbstractODEProblem{uType,tType,isinplace,F}, ::T<:OrdinaryDiffEq.OrdinaryDiffEqAlgorithm, ::Any, ::Any) at C:\Users\thiem\.julia\v0.5\OrdinaryDiffEq\src\solve.jl:20
```

It seems that there is no solve function which can choose its solving algorthm by itself. If I try the next line 
`sol = solve(prob,Euler(),dt=1/2^4)` everything works fine. Has there been a change in the API, that has not been reflected in the tutorial?

**Comment by ChrisRackauckas** [comment]
```julia
using DifferentialEquations
α=1
u0=1/2
f(t,u) = α*u
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob)
```

Just ran it an it works. There hasn't been an API change to this in a very long time. Did you `using DifferentialEquations`, or `using DiffEqBase, OrdinaryDiffEq`? DifferentialEquations is required for the default algorithm mechanism.

**Comment by ChrisRackauckas** [comment]
I would restart Julia and run that exact code. If something weird is going on, it might be easier to debug this in the chatroom:

https://gitter.im/JuliaDiffEq/Lobby

**Comment by Tyde** [comment]
Hm.. I ran the same code and got this error
![grafik](https://cloud.githubusercontent.com/assets/1103207/24791526/b188a894-1b7a-11e7-977e-4ffabdc99b51.png)

I will ask in the gitter chatroom

**Comment by Tyde** [comment]
Error occured, because I used an old version of DifferntialEquations. With the current version, it works! Thanks for the help.
