### ISSUE TITLE
SDE Example does not work in Julia 1.0.3

### ISSUE THREAD

**Issue by WouterJRV** [JuliaDiffEq/DiffEqDocs.jl#217]
When I try 
```
f(::Type{Val{:analytic}},u,p,t₀,W) = u₀*exp((α-(β^2)/2)*t+β*W)
prob = SDEProblem(f,g,u₀,(0.0,1.0))
sol = solve(prob,EM(),dt=dt)
plot(sol,plot_analytic=true)
```
as described in http://docs.juliadiffeq.org/latest/tutorials/sde_example.html under "using higher order methods", Juno gives me the error below. Is this a compatibility issue?

> UndefVarError: t not defined
> f(::Type{Val{:analytic}}, ::Float64, ::Nothing, ::Float64, ::Float64) at untitled-4df9026e7d3e342ffd1134d501727256:17
> (::getfield(DiffEqBase, Symbol("##224#230")){typeof(f)})(::Float64, ::Vararg{Any,N} where N) at diffeqfunction.jl:718
> #calculate_solution_errors!#21(::Bool, ::Bool, ::Bool, ::Function, ::RODESolution{Float64,1,Array{Float64,1},Array{Float64,1},Dict{Symbol,Float64},Array{Float64,1},NoiseProcess{Float64,1,Float64,Float64,Nothing,Nothing,typeof(DiffEqNoiseProcess.WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.WHITE_NOISE_BRIDGE),false,DataStructures.Stack{Tuple{Float64,Float64,Nothing}},ResettableStacks.ResettableStack{Tuple{Float64,Float64,Nothing},false},RSWM{:RSwM1,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},SDEProblem{Float64,Tuple{Float64,Float64},false,Nothing,Nothing,SDEFunction{false,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},getfield(DiffEqBase, Symbol("##224#230")){typeof(f)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Nothing,Nothing},EM{true},StochasticDiffEq.LinearInterpolationData{Array{Float64,1},Array{Float64,1}}}) at rode_solutions.jl:72
> #calculate_solution_errors! at none:0 [inlined]
> solve!(::StochasticDiffEq.SDEIntegrator{EM{true},false,Float64,Float64,Float64,Nothing,Float64,Float64,Float64,NoiseProcess{Float64,1,Float64,Float64,Nothing,Nothing,typeof(DiffEqNoiseProcess.WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.WHITE_NOISE_BRIDGE),false,DataStructures.Stack{Tuple{Float64,Float64,Nothing}},ResettableStacks.ResettableStack{Tuple{Float64,Float64,Nothing},false},RSWM{:RSwM1,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Float64,RODESolution{Float64,1,Array{Float64,1},Array{Float64,1},Dict{Symbol,Float64},Array{Float64,1},NoiseProcess{Float64,1,Float64,Float64,Nothing,Nothing,typeof(DiffEqNoiseProcess.WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.WHITE_NOISE_BRIDGE),false,DataStructures.Stack{Tuple{Float64,Float64,Nothing}},ResettableStacks.ResettableStack{Tuple{Float64,Float64,Nothing},false},RSWM{:RSwM1,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},SDEProblem{Float64,Tuple{Float64,Float64},false,Nothing,Nothing,SDEFunction{false,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},getfield(DiffEqBase, Symbol("##224#230")){typeof(f)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Nothing,Nothing},EM{true},StochasticDiffEq.LinearInterpolationData{Array{Float64,1},Array{Float64,1}}},StochasticDiffEq.EMConstantCache,SDEFunction{false,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},getfield(DiffEqBase, Symbol("##224#230")){typeof(f)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),StochasticDiffEq.SDEOptions{Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Float64,Float64,Float64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Nothing,Float64}) at solve.jl:405
> #__solve#41(::Base.Iterators.Pairs{Symbol,Rational{Int64},Tuple{Symbol},NamedTuple{(:dt,),Tuple{Rational{Int64}}}}, ::Function, ::SDEProblem{Float64,Tuple{Float64,Float64},false,Nothing,Nothing,SDEFunction{false,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},getfield(DiffEqBase, Symbol("##224#230")){typeof(f)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Nothing,Nothing}, ::EM{true}, ::Array{Any,1}, ::Array{Any,1}, ::Nothing, ::Type{Val{true}}) at solve.jl:7
> #__solve at none:0 [inlined]
> #__solve at none:0 [inlined]
> #__solve at none:0 [inlined]
> #__solve at none:0 [inlined]
> #__solve at none:0 [inlined]
> #solve#429(::Base.Iterators.Pairs{Symbol,Rational{Int64},Tuple{Symbol},NamedTuple{(:dt,),Tuple{Rational{Int64}}}}, ::Function, ::SDEProblem{Float64,Tuple{Float64,Float64},false,Nothing,Nothing,SDEFunction{false,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},getfield(DiffEqBase, Symbol("##224#230")){typeof(f)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Nothing,Nothing}, ::EM{true}) at solve.jl:39
> (::getfield(DiffEqBase, Symbol("#kw##solve")))(::NamedTuple{(:dt,),Tuple{Rational{Int64}}}, ::typeof(solve), ::SDEProblem{Float64,Tuple{Float64,Float64},false,Nothing,Nothing,SDEFunction{false,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},getfield(DiffEqBase, Symbol("##224#230")){typeof(f)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Nothing,Nothing}, ::EM{true}) at none:0
> top-level scope at none:0
>

**Comment by ChrisRackauckas** [comment]
The way of defining an analytical solution changed so that needs an update.

**Comment by WouterJRV** [comment]
> The way of defining an analytical solution changed so that needs an update.

I don't think that's the whole story, as the same error persists if I only execute the middle two lines?

**Comment by GantZA** [comment]
theres a typo in `f(::Type{Val{:analytic}},u,p,t₀,W) = u₀*exp((α-(β^2)/2)*t+β*W)` I think. 
Look at `u₀` and `t₀`
It should be `f(::Type{Val{:analytic}},u₀,p,t,W) = u₀*exp((α-(β^2)/2)*t+β*W)`

**Comment by WouterJRV** [comment]
> theres a typo in `f(::Type{Val{:analytic}},u,p,t₀,W) = u₀*exp((α-(β^2)/2)*t+β*W)` I think.
> Look at `u₀` and `t₀`
> It should be `f(::Type{Val{:analytic}},u₀,p,t,W) = u₀*exp((α-(β^2)/2)*t+β*W)`

That does the trick, thanks!

**Comment by ChrisRackauckas** [comment]
Fixed.
