### ISSUE TITLE
Update Global Sensitivity docs

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaDiffEq/DiffEqDocs.jl#279]
Major changes recently, the docs need to be updated.

**Comment by stevengogogo** [comment]
**Wrong spelling**

`using DiffEqSensitivty` should be `using DiffEqSensitivity`

**The Struct "morris_sensitivity" has been removed.**  

I use the following code for the same work:
`m = DiffEqSensitivity.gsa(prob,
                     Tsit5(),
                      t,
                     [[1,5],[0.5,5]],
                     DiffEqSensitivity.Morris());`

**Comment by Vaibhavdixit02** [comment]
Yeah, I am a bit occupied right now. I will get to updating this soon 👍
