### ISSUE TITLE
Standard behaviour EnsembleAlgorithms

### ISSUE THREAD

**Issue by ArnoStrouwen** [JuliaDiffEq/DiffEqDocs.jl#291]
In the ensemble section, the EnsembleAlgorithms subsection states that `EnsembleThreads()` is the default. It also states that `EnsembleDistributed()` uses `pmap` internally.

Further down the same page in Example 1 states that the example will use pmap (which I interpret, from the above, that we want to use `EnsembleDistributed()`). Yet no `EnsembleAlgorithms` is specified:
```
ensemble_prob = EnsembleProblem(prob,prob_func=prob_func)
sim = solve(ensemble_prob,Tsit5(),trajectories=100)
```
So the default `EnsembleThreads()` will be used instead? This is not very clear to me.
I also did not notice any parallel computation with the above example without specifying `EnsembleDistributed()` (with `JULIA_NUM_THREADS = 1`).

**Comment by ChrisRackauckas** [comment]
That was a mistake, it should've had `EnsembleDistributed()` in there. Thanks!
