### ISSUE TITLE
using DifferentialEquations.OrdinaryDiffEq instad of using OrdinaryDiffEq

### ISSUE THREAD

**Issue by unevens** [JuliaDiffEq/DiffEqDocs.jl#293]
In the document https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/src/features/low_dep.md it says that when using only the ODE solvers OrdinaryDiffEq.jl you can use 

```julia
using OrdinaryDiffEq
```

Doing so in a REPL session got me

```
ERROR: ArgumentError: Package OrdinaryDiffEq not found in current path:
- Run `import Pkg; Pkg.add("OrdinaryDiffEq")` to install the OrdinaryDiffEq package.
```

Instead, doing 

```julia
using DifferentialEquations.OrdinaryDiffEq
```

works as exepcted.

Maybe the documentation could be updated. 

Or maybe I'm missing something, I'm a beginner with Julia.

**Comment by ChrisRackauckas** [comment]
For the low dependency usage, you need to add the `OrdinaryDiffEq.jl` package before using it. DifferentialEquations.jl is simply using OrdinaryDiffEq.jl for the ODE solvers, so if you do `]add OrdinaryDiffEq` then it will just make it available to you without having to actually download anything. Hopefully this little blurb:

https://github.com/JuliaDiffEq/DiffEqDocs.jl/commit/2e8a4bc1230d3a329f6d0169cb6247488a5abaed

makes it more clear. Let me know if I should add more to this discussion.

**Comment by unevens** [comment]
Crystal clear. Thanks!
