### ISSUE TITLE
Broken link : the eternal saga

### ISSUE THREAD

**Issue by klaff** [JuliaDiffEq/DiffEqDocs.jl#295]
At http://docs.juliadiffeq.org/latest/tutorials/sde_example/#Example-3:-Systems-of-SDEs-with-Scalar-Noise-1, the link [using the Noise Process interface](http://docs.juliadiffeq.org/latest/tutorials/features/noise_process.html) is broken.

**Comment by ChrisRackauckas** [comment]
It looks like all of the links broke in this morning's documentation update 🤦‍♂ . @kanav99 said he's on it.
