### ISSUE TITLE
Add canonical links to stable for all previously deployed docs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDocs.jl#305]
https://github.com/JuliaDiffEq/DiffEqDocs.jl/pull/304#issuecomment-557472754

@fredrikekre suggests @mortenpi has an answer. Would make the search engines prefer replacing all older version doc links with the newer versions.

**Comment by mortenpi** [comment]
This is what we ended up doing for the Base docs: https://github.com/JuliaLang/docs.julialang.org/pull/11/files

That tag would have to be added in with `sed` or something like that.

**Comment by ChrisRackauckas** [comment]
Handled by https://github.com/JuliaDiffEq/DiffEqDocs.jl/pull/312
