### ISSUE TITLE
The same examples of ODE parameters' estimation are not working anymore

### ISSUE THREAD

**Issue by ahmadjordan** [JuliaDiffEq/DiffEqDocs.jl#339]
Given that the package `ParmaeterizedFunctions` has got a new syntax. How the current examples in here https://docs.juliadiffeq.org/v1.6/analysis/parameter_estimation.html will be updated to run accordingly.

**Comment by ChrisRackauckas** [comment]
Those examples you linked to are not current. You're linking to the v1.6 documentation from 3 years ago. Please use the current version of the documentation and you will be good.
