### ISSUE TITLE
Fill out Dynamical ODE docs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDocs.jl#34]
The `DynamicalODEProblem` types all have sufficient documentation of their definition and solvers now. However, there's things which are missing:

- [x] A tutorial on dynamical ODEs, showing how to define them, the differences between non-symplectic and symplectic methods, and showing how to use the `ArrayPartition`
- [x] A description of the `NBodyProblem` with an example in the Physical Models page.

@YingboMa would you like to contribute these pages?

**Comment by YingboMa** [comment]
Yeah, sure.
