### ISSUE TITLE
Limits of the parameterized functions macro

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaDiffEq/DiffEqDocs.jl#56]
The documentation of the `@ode_def` macro should include that the independent variable can be addressed via `t` for the sake of non-autonomous ODEs.
Also a short of example of how to provide a derivative of a user defined function would be good.
Finally a paragraph ( or section? ) about limits of the macro ( e.g. can't handle branching ) should be added.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DiffEqDocs.jl/commit/dd378e07bc45ac0c87a81ff49c5f7c913b33c63b
