### ISSUE TITLE
broken links on http://docs.juliadiffeq.org/latest/basics/overview.html

### ISSUE THREAD

**Issue by johnfgibson** [JuliaDiffEq/DiffEqDocs.jl#59]
A few links in the basics/overview.html page are broken due to an extra "basics/" in the URL. For example, in the "Solving the Problems" subsection of ,http://docs.juliadiffeq.org/latest/basics/overview.html, the "common solver options manual page" link points to  http://docs.juliadiffeq.org/latest/basics/basics/common_solver_opts.html, where it should point to http://docs.juliadiffeq.org/latest/basics/common_solver_opts.html. Similarly for "solution handling manual page" in the "Analyzing the Solution" subsection.

The relevant Markdown for the first example is line 49 of master/docs/src/basics/overview.md
```
arguments which are accepted by most methods is defined in [the common solver options manual page](common_solver_opts.html).
```
so it must be some issue in Markdown resolving relative links.

**Comment by ChrisRackauckas** [comment]
Thanks. This can probably be fixed by using the `@ref` thing from Documenter.

**Comment by ChrisRackauckas** [comment]
Couldn't change to `@ref` without changing the name in the link... so I just did the simple link fix of adding "../". Thanks for pointing this out!

**Comment by johnfgibson** [comment]
Sampling other pages I found a few similar instances, but I'm sure my coverage is incomplete. Perhaps an automated link explorer is in order. 

A list of broken links

On http://docs.juliadiffeq.org/latest/basics/common_solver_opts.html,  under "Common Solver Options"
"compatibility chart" -> http://docs.juliadiffeq.org/latest/basics/basics/compatibility_chart.html,

Same page as above, under "Miscellaneous", "Event Handling and Callback Functions manual page" -> http://docs.juliadiffeq.org/latest/man/callback_functions.html

On http://docs.juliadiffeq.org/latest/features/diffeq_arrays.html,  "DiscreteCallback interface" -> http://docs.juliadiffeq.org/latest/features/features/callback_functions.html 

On http://docs.juliadiffeq.org/latest/analysis/parameter_estimation.html,  under "Local Optimization Examples",  "documentation for Optim.jl" -> http://www.juliaopt.org/Optim.jl/latest/

You're welcome; I'm glad to be able to contribute. If I were more on the ball, I'd be filing pull requests with fixes. But figuring out exactly how Markdown is going wrong and verifying correctness of the fix is a little beyond me right now.

**Comment by ChrisRackauckas** [comment]
Thanks! Fixed those. Let me know if you find any more. An automated link explorer would be amazing.

**Comment by nmatzke** [comment]
Hi! Fantastic page!  This link appears to still be broken:

========
For a comprehensive list of the available algorithms and detailed recommendations, Please see the solver documentation. Every problem type has an associated page detailing all of the solvers associated with the problem.
========

The text "Please see the solver documentation." links to https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/solvers/ode_solve.html , but this page gives a 404 error.

**Comment by ChrisRackauckas** [comment]
Where? On http://docs.juliadiffeq.org/latest/tutorials/ode_example.html#Choosing-a-Solver-Algorithm-1 it seems fine.

**Comment by nmatzke** [comment]
Hi -- apologies, I was looking at:

https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/src/tutorials/ode_example.md

where the link doesn't work.

...but I guess:

http://docs.juliadiffeq.org/latest/tutorials/ode_example.html

is the one I should be looking at. Thanks! Nick
