### ISSUE TITLE
PCE docs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDocs.jl#83]
@onoderat docs are needed on the SDE solvers page for PCE and the definition of gg'

**Comment by onoderat** [comment]
Ok working on it now.

**Comment by ChrisRackauckas** [comment]
No rush!

**Comment by onoderat** [comment]
Actually now that I think about it, I am gonna do the documentation after I get confirmation for the form of ggprime that I concluded. Going to send the emails out to Platen now.

**Comment by ChrisRackauckas** [comment]
Alright. Also ask about how it's written in matrix form and see if he's thought about that.

**Comment by onoderat** [comment]
Got email confirmation from Platen that the formula I proposed is the correct one. 
Added the documentation in the docs.
