### ISSUE TITLE
Parameter estimation: build_optim_objective

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqDocs.jl#9]
In the forthcoming parameter estimation notebook, the idea is to give in the md text the menu of options for each module used to build the optimization problem. For LeastSquaresOptim, this is simple with just a few clarifications that I requested from Matthieu Gomez. 

For Optim, this proves more difficult and I cannot sort out what is linked to Optim and what is linked to build_optim_objective. In short, look at this:

result = optimize(cost_function, [1.02], LBFGS()) #Working
#result = optimize(cost_function, [1.02], LBFGS(), Optim.Options(autodiff = use_autodiff))
#result = optimize(cost_function, [1.02], Optim.Options(autodiff = true)) #not working
#result = optimize(cost_function, [1.02], BFGS(), Optim.Options(autodiff = use_autodiff)) #not working
#result = optimize(cost_function, [1.02], Newton(), Optim.Options(autodiff = true)) # not working

My aim is to have a simple menu of methods: Brent, Newton, BFGS, LBFGS etc... and a simple menu of options for each menu. All of this working 100 percent of the time, otherwise we should get a flag saying that the combination is not appropriate.

**Comment by ChrisRackauckas** [comment]
Try using the ls_optim objective with Optim.jl. It may make autodiff work.

**Comment by finmod** [comment]
Does not work. This is the object of https://github.com/matthieugomez/LeastSquaresOptim.jl/issues/8

**Comment by ChrisRackauckas** [comment]
Hmm. I thought autodiff through the method was working. Maybe have broke with some of the integrator changes. What's the error?

**Comment by finmod** [comment]
Here is a complete run of the various combinations of solvers in Optim. Brent and Goldensection are not included here since they are special methods for univariate optimization. For multivariate, NelderMead and SimulatedAnnealing work as expected with just a function handle. Then:

 #result = optimize(cost_function, [1.02, 0.8, 3.5, 1.5], BFGS()) # Pass.
#result = optimize(cost_function, [1.02, 0.8, 3.5, 1.5], BFGS(), Optim.Options(autodiff = true)) # Fail.TypeError: setfield!: expected Float64, got ForwardDiff.Dual{4,Float64}
result = optimize(cost_function, [1.02, 0.8, 3.5, 1.5], LBFGS()) # Pass.
#result = optimize(cost_function, [1.02, 0.8, 3.5, 1.5], ConjugateGradient()) # Pass.
#result = optimize(cost_function, [1.02, 0.8, 3.5, 1.5], GradientDescent()) # Pass.
#result = optimize(cost_function, [1.02, 0.8, 3.5, 1.5], MomentumGradientDescent()) # Pass.
#result = optimize(cost_function, [1.02, 0.8, 3.5, 1.5], AcceleratedGradientDescent()) # Pass.
#result = optimize(cost_function, [1.02, 0.8, 3.5, 1.5], Newton()) # Fail. No gradient or Hessian was provided. Either provide a gradient and Hessian, set autodiff = true in the Options if applicable, or choose a solver that doesn't require a Hessian.
#result = optimize(cost_function, [1.02, 0.8, 3.5, 1.5], Newton(), Optim.Options(autodiff = true)) # Fail.TypeError: setfield!: expected Float64, got ForwardDiff.Dual{4,Float64}

According to Optim.docs, BFGS with autodiff option should work. Newton requires a function, a gradient and a Hessian that cannot be omitted. It would be good to try an ode_def_with Hessian for Lotke-Volterra here. Otherwise, Newton with autodiff option should work and it does not. This might be an Optim problem.

**Comment by ChrisRackauckas** [comment]
I'll look into the autodiff.

The Hessian is not an option. The Hessian wouldn't be the Hessian of the ODE system, rather it would have to be the Hessian of the ODE solution minus the cost function, which is not something that is feasibly able to be computed symbolically. Autodifferentiation? I'll see if I can get that working.

**Comment by ChrisRackauckas** [comment]
I generalized the cost function a bit so that way autodiff would work.

But also... it works with other packages now. See the new docs which includes some global optimization!

http://docs.juliadiffeq.org/latest/analysis/parameter_estimation.html#More-Algorithms-(Global-Optimization)-via-MathProgBase-Solvers-1
