### ISSUE TITLE
Cannot use the `I` symbol in the SIR example

### ISSUE THREAD

**Issue by Armavica** [JuliaDiffEq/DiffEqDocs.jl#94]
On Julia `0.6.3-pre.0`, defining the SIR model as indicated in the tutorial yields

> ERROR: ArgumentError: Second argument must be of Symbol type

which disappears when `I` is changed into something else which does not already have a meaning in Julia.

**Comment by ChrisRackauckas** [comment]
Oh... the actual test I took this from used `s`, `i`, `r` so let's change that back.

**Comment by ChrisRackauckas** [comment]
Thanks! The docs are updated. Feel free to open another issue if there's more problems.
