### ISSUE TITLE
SIR example is unclear about the order of the variables

### ISSUE THREAD

**Issue by Armavica** [JuliaDiffEq/DiffEqDocs.jl#95]
> Here, we will start with 999 susceptible people, 1 infected person, and 0 recovered people

This line justifies the initial value `[999, 1, 0]` but just from the docs it is unclear to me why the variable are ordered this way. Is it the order where they appear in the model?

**Comment by ChrisRackauckas** [comment]
Yeah, it's the order they appear in the model. Thanks for pointing this out. We'll get the docs updated.

**Comment by ChrisRackauckas** [comment]
Thanks! The docs are updated. Feel free to open another issue if there's more problems.
